### ISSUE TITLE
Link to user guide broken

### ISSUE THREAD

**Issue by krosenfeld-IDM** [VERSE-Equity/Toolkit-DHS#1]
In the README, the link to the user guide appears to be broken in 2 places:
https://github.com/VERSE-Equity/Toolkit-DHS/blob/a75ddc7dee89dc4b2536f095f825b9bc2b0977dd/README.md?plain=1#L212
https://github.com/VERSE-Equity/Toolkit-DHS/blob/a75ddc7dee89dc4b2536f095f825b9bc2b0977dd/README.md?plain=1#L228

**Comment by gdebroucker** [comment]
Thank you for letting us know! The links were replaced.
