### ISSUE TITLE
Error in ci

### ISSUE THREAD

**Issue by cathy-eunhyelee** [VERSE-Equity/Toolkit-DHS#2]
Hello. I am trying to run the VERSE Equity Tool with the 2017-8 DHS Data for Bangladesh. When I source the code, the below error appears. I have downloaded all the packages and am using the latest version of all programs.

**Error in ci(y = data_i[, i], x = pred_probs_2$hci_du.response, wt = data_i$v005,  : 
  unused arguments (y = data_i[, i], x = pred_probs_2$hci_du.response, wt = data_i$v005)**

Please let me know how I can resolve this. Thank you.

**Comment by gdebroucker** [comment]
Thank you for reaching out and letting us know. There could be two possible solutions to this issue:

(1) you can try to uninstall and reinstall the "dplyr" package in R (the program uses dplyr heavily for all data wrangling, and any alteration to the original R package may interact with it), or

(2, but likely doesn't apply here) if you have an older version of the VERSE.R program, it asks you to install and use the package called "StatMeasure". you should remove this line (the latest (10/2023) version of VERSE.R already removed it).

If it does not resolve the issue, please let us know and we will review it further.

**Comment by cathy-eunhyelee** [comment]
Hello. Thank you very much for the reply.

As I just downloaded the latest VERSE.R that doesn't include "StatMeasure" package, I tried the first solution. But unfortunately, the error still appears.

For your information, I am using R Version 4.3.2 and R Studio Version 2023.12.1+402 for MacOS.

Thank you for your time to review this issue.

**Comment by gdebroucker** [comment]
Issue was resolved over email.
